language: php

php:
    - '7.1'
    - '7.2'

install:
    - composer install

script:
    - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
    - ./vendor/bin/phpstan analyze .

after_script:
    - php vendor/bin/php-coveralls -v

cache:
    directories:
        - vendor/